###############################################################################
############{@Authors[Cixxor,TheoLs], ConfigurationFile:[HubGames]}############
###############################################################################
worldname: "world"
pvp:
  cuboid:
    x1: 0
    y1: 0
    z1: 0
    x2: 0
    y2: 0
    z2: 0
spleef:
  cuboid:
    x1: 0
    y1: 0
    z1: 0
    x2: 0
    y2: 0
    z2: 0
archery:
  cuboid:
    x1: 0
    y1: 0
    z1: 0
    x2: 0
    y2: 0
    z2: 0
blockparty:
  cuboid:
    x1: 0
    y1: 0
    z1: 0
    x2: 0
    y2: 0
    z2: 0
race:
  cuboid:
    x1: 0
    y1: 0
    z1: 0
    x2: 0
    y2: 0
    z2: 0  